project:
  type: book

book:
  title: "laggedcor Tutorial"
  author: "Xiaotao SHEN & Zirui QIANG & Shunpeng BAI & Yitong WU"
  date: "2025-08-04"
  sidebar:
    logo: images/laggedcor_logo.png    
    style: "docked"                     
    collapse-level: 1                   
  repo-url: https://github.com/ZiruiQIANG/laggedcor-tutorial
  repo-branch: main
  repo-actions: [edit, issue, source]   
  chapters:
    - index.qmd
    - 1-1-installation.qmd
    - 1-2-update.qmd
    - 1-3-docker_laggedcor.qmd
    - 1-4-build_own_docker.qmd
    - 2-1-create_dataset.qmd
    - 2-2-add_metadata.qmd
    - 2-3-dataset_other_tools.qmd
    - 2-4-extract.qmd
    - 2-5-processing_information.qmd
    - 3-1-shiny_module.qmd
    - 3-2-data_convert.qmd
    - 4-1-analysis_workflow.qmd
    - references.qmd

format:
  html:
    theme: flatly          
    toc: true              
    number-sections: false 
    title-block-style: default
    title-block-banner: false